DROP TABLE conditions CASCADE CONSTRAINT;
DROP TABLE devices CASCADE CONSTRAINT;
DROP TABLE diagnoses CASCADE CONSTRAINT;
DROP TABLE genomes CASCADE CONSTRAINT;
DROP TABLE measurements CASCADE CONSTRAINT;
DROP TABLE mri_scans CASCADE CONSTRAINT;
DROP TABLE patients CASCADE CONSTRAINT;
DROP TABLE physicians CASCADE CONSTRAINT;
DROP TABLE regimens CASCADE CONSTRAINT;
DROP TABLE technicians CASCADE CONSTRAINT;
DROP TABLE treatments CASCADE CONSTRAINT;
DROP TABLE users CASCADE CONSTRAINT;
DROP TABLE visits CASCADE CONSTRAINT;

exit
